name       : audit
version    : 3.0.7
release    : 9
source     :
    - https://github.com/linux-audit/audit-userspace/archive/refs/tags/v3.0.7.tar.gz : 0ff0dfb64b29b55966d7a1aa938dbc9e629b781bf3e8fd31ea1f58982bd41777
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.base
summary    : audit daemon and libraries
description: |
    Provides the auditd daemon and libraries for the CONFIG_AUDIT interface
setup      : |
    %reconfigure --with-apparmor=yes \
        --disable-zos-remote \
        --with-python3=no \
        --with-python=no \
        --disable-static \
        --sbindir=/sbin \
        --enable-systemd=yes
build      : |
    %make
install    : |
    %make_install
    install -d -D -m 00755 $installdir/usr/lib/systemd/system/multi-user.target.wants
    ln -sv ../auditd.service $installdir/usr/lib/systemd/system/multi-user.target.wants/auditd.service
    install -D -m 00644 $pkgfiles/audit.tmpfiles $installdir/%libdir%/tmpfiles.d/audit.conf
