name       : audit
version    : 2.8.1
release    : 1
source     :
    - https://people.redhat.com/sgrubb/audit/audit-2.8.1.tar.gz : 1becde92ff6e81798fa8878820ab2497d867036a6596f55109504b37c8b33b6c
license    :
    - GPL-2.0
    - LGPL-2.1
component  : security.library
summary    : audit daemon and libraries
description: |
    Provides the auditd daemon and libraries for the CONFIG_AUDIT interface
setup      : |
    %configure --with-apparmor=yes \
               --disable-zos-remote \
               --with-python3=no \
               --with-python=no \
               --disable-static \
               --sbindir=/sbin \
               --enable-systemd=yes
build      : |
    %make
install    : |
    %make_install
    install -d -D -m 00755 $installdir/usr/lib/systemd/system/multi-user.target.wants
    ln -sv ../auditd.service $installdir/usr/lib/systemd/system/multi-user.target.wants/auditd.service
    install -D -m 00644 $pkgfiles/audit.tmpfiles $installdir/%libdir%/tmpfiles.d/audit.conf
